### ISSUE TITLE
Create a Discord Bot for Semaphore

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/discord-bot#1]
**Tasks**:

- [x] Create `get-group` command
- [x] Improve UX
- [x] Integrate Lint/Prettier/Conventional Commits
- [x] Update README file
- [x] Refine code
